"""empty message

Revision ID: cf146e1097ac
Revises: 
Create Date: 2020-11-24 13:09:23.508090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf146e1097ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vacancy_id', sa.String(length=64), nullable=True),
    sa.Column('vacancy_name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('company', sa.String(length=128), nullable=False),
    sa.Column('salary_from', sa.Integer(), nullable=True),
    sa.Column('salary_to', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('skill_set', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('specialization', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancy_vacancy_id'), 'vacancy', ['vacancy_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_vacancy_id'), table_name='vacancy')
    op.drop_table('vacancy')
    # ### end Alembic commands ###
